import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

import { WeatherProvider } from "@/providers/WeatherProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { UnitsProvider } from "@/providers/UnitsProvider";

// Google Font
const lato = Lato({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable} suppressHydrationWarning>
      <body className={`tracking-wide antialiased`}>
        <WeatherProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <UnitsProvider>
              <h1 className="sr-only">Weather App</h1>
              <div className="container py-4">{children}</div>
            </UnitsProvider>
          </ThemeProvider>
        </WeatherProvider>
      </body>
    </html>
  );
}
