import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/ThemeProvider";
import { WeatherProvider } from "@/providers/WeatherProvider";

// Google Font
const lato = Lato({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <h1 className="sr-only">Weather App</h1>
          <div className="container">
            <WeatherProvider>{children}</WeatherProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
